@startuml
'https://plantuml.com/class-diagram

class Jeu

abstract Personnage{
#pos: Position
Position getPos()
}
class Hero{
-pos: Position
+Hero()
+getPos(): Postion
+deplacer()
}

class Labyrinth{
-grille: char[][]
-hero:Hero
+Labyrinth(String fichier)
+estLibre(int x, int y): boolean
+getGrille(): char[][]
+getHero(): Hero
+
}
class JeuPerso{
}
class LabyrinthDessin{
}

class DessinJeu{
}
class DessinPerso{
-jeu: JeuPerso
+dessiner(BufferedImage im)
+getJeu(): JeuPerso
}
class JeuPerso{
}

Hero ..> Personnage
Personnage --> MainPerso
Labyrinth --> MainPerso
Jeu ..> JeuPerso
DessinJeu-->MainPerso
JeuPerso..>MainPerso
LabyrinthDessin..>DessinJeu


@enduml