@startuml
'https://plantuml.com/sequence-diagram

autonumber


@startuml
title déplacement
autonumber

Main -> JeuPerso: initialisation()
JeuPerso -> Labyrinthe: creation()
Joueur -> JeuPerso: Touche ZQSD
JeuPerso->Hero:déplacer()






@enduml