'https://plantuml.com/sequence-diagram
@startuml

participant main
participant personnage

main -> personnage : attaquer((degat:int)
personnage --> main : degat : int

main -> personnage : recevoirDegat()

personnage --> main : vie : int


@enduml