@startuml
'https://plantuml.com/sequence-diagram

autonumber


@startuml
title déplacement
autonumber



MainPerso -> Labyrinthe: creation(fichier.txt)
MainPerso-> JeuPerso:evoluer(commande)
Joueur -> JeuPerso: Touche ZQSD
JeuPerso->Hero:déplacer(int x , int y)
Hero --> JeuPerso:
JeuPerso-->MainPerso:
Labyrinthe-->MainPerso:




@enduml