@startuml
'https://plantuml.com/class-diagram

class Jeu

interface Personnage{
+seDeplacer()
+attaquer():int
}
class Heros{
-vie:int
+attaquer()
+seSoigner()
}
class Monstre{
-vie:int
+attaquer()
}

class Labyrinth{
-Case case
}
class Case{
-mur: boolean
}

Heros -> Personnage
Monstre -> Personnage
Personnage -> Jeu
Case -> Labyrinth
Labyrinth -> Jeu



@enduml