@startuml
'https://plantuml.com/sequence-diagram

autonumber


@startuml
autonumber

Main -> JeuPerso: initialisation()
JeuPerso -> Labyrinthe: creation()


JeuPerso -> Labyrinthe: getCoordonneesVides()
Labyrinthe --> JeuPerso: x, y


JeuPerso -> Monstre: new Monstre(x, y)
JeuPerso <-- Monstre:
JeuPerso -> JeuPerso: definir_monstre()

@enduml