@startuml


participant "JeuPerso"
participant "Hero"
participant "Labyrinthe"
participant "PorteSortie"
participant "Monstre"
participant "System"
participant "Phantome"







"JeuPerso" -> Monstre : estVivant()
Monstre --> "JeuPerso" : false

JeuPerso -> Hero : estVivant()
Hero --> "JeuPerso" : true

"JeuPerso" -> "Phantome":estVivant()
"Phantome"--> "JeuPerso":true
alt hero sur porte ET monstre mort
    JeuPerso ->System : print("VICTOIRE")
    System --> JeuPerso : victoire
else
    JeuPerso -> JeuPerso : continuer jeu
end



@enduml