@startuml
autonumber
hide footbox

participant "jeu : JeuPerso" as jeu
participant "phantome : Phantome" as phantome
participant "random : Random" as random
participant "labyrinthe : Labyrinthe" as labyrinthe

-> jeu : evoluer(c)
activate jeu

jeu -> phantome : deplacer(labyrinthe)
activate phantome

phantome -> phantome : estVivant()
activate phantome
phantome --> phantome : boolean (true)
deactivate phantome

alt cooldown == 0
    phantome -> random : nextInt(4)
    activate random
    random --> phantome : int (choix)
    deactivate random

    phantome -> labyrinthe : estLibrePhantome(nx, ny)
    activate labyrinthe
    labyrinthe --> phantome : boolean (libre)
    deactivate labyrinthe

    alt libre == true
        phantome -> phantome : pos.x = nx \n pos.y = ny
    end

    phantome -> phantome : cooldown = 4
end

jeu <-- phantome
deactivate phantome

<-- jeu
deactivate jeu
@enduml
