@startuml
autonumber
hide footbox

participant "jeu : JeuPerso" as jeu
participant "phantome : Phantome" as phantome
participant "random : Random" as random
participant "labyrinthe : Labyrinthe" as labyrinthe

jeu -> phantome : deplacer(labyrinthe)
activate phantome

phantome -> phantome : estVivant()
activate phantome
phantome --> phantome : boolean (true)
deactivate phantome

alt cooldown == 0
    phantome -> random : nextInt(4)
    activate random
    random --> phantome : choix (int)
    deactivate random

    phantome -> phantome : calcul_nx_ny

    phantome -> labyrinthe : estLibrePhantome(nx, ny)
    activate labyrinthe
    labyrinthe --> phantome : boolean
    deactivate labyrinthe

    alt estLibrePhantome == true
        phantome -> phantome : mise à jour pos.x et pos.y
    end

    phantome -> phantome : cooldown = 4
end

jeu <-- phantome
deactivate phantome
@enduml