@startuml


participant "JeuPerso" as Jeu
participant "Hero" as Hero
participant "Labyrinthe" as Lab
participant "PorteSortie" as Porte
participant "Monstre" as Monstre
participant "System" as Sys



Jeu -> Hero : getPos()
Hero --> Jeu : (x, y)

Jeu -> Lab : estLibre(nx, ny)
Lab --> Jeu : true/false

Jeu -> Hero : deplacer(nx, ny)
Hero --> Jeu : ok

Jeu -> Porte : verifierCollision(hero)
Porte -> Monstre : estVivant()
Monstre --> Porte : false

Porte -> Hero : estVivant()
Hero --> Porte : true

Porte --> Jeu : collisionOK / collisionKO

alt hero sur porte ET monstre mort
    Jeu -> Sys : print("VICTOIRE")
    Sys --> Jeu : affichage OK
else
    Jeu -> Jeu : continuer jeu
end

Jeu --> Joueur : frame suivante

@enduml