@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant main


participant hero


participant monstre

main -> hero : attaquer((degat:int)
hero -> monstre : recevoirDegat.(degat:int)
monstre --> hero : vie : int
hero --> main
@enduml