@startuml
title attaque
actor Joueur

participant JeuPerso
participant Hero
participant Monstre

== Attaque directionnelle ==

Joueur -> JeuPerso : appuie F / T / G / H

JeuPerso -> Hero : attaquer(monstre, direction)

JeuPerso -> JeuPerso : Trouver Cible  (int x , int x)

JeuPerso -> Monstre : vérifier position


alt monstre sur case ciblée
    Hero -> Monstre : subirdegat(dégâts)
    Monstre -> Monstre : vie -= dégâts
else aucune cible
    Hero -> Hero : attaque ratée
end

@enduml