@startuml



participant MainPerso
participant Labyrinthe
participant Hero
participant Monstre
participant JeuPerso
participant MoteurGraphique

== Lancement du jeu ==



MainPerso -> Labyrinthe : new Labyrinthe(labyrinthe.txt)

Labyrinthe -> Hero : création héros (x,y,PV)
Labyrinthe -> Monstre : création monstre (x,y,PV)

MainPerso -> JeuPerso : new JeuPerso(labyrinthe)
MainPerso -> MoteurGraphique : lancerJeu()



== Déplacement du monstre ==

loop chaque frame

    MoteurGraphique -> JeuPerso : evoluer()

    JeuPerso -> Monstre : deplacer(labyrinthe)

    Monstre -> Monstre : choisir direction aléatoire

    Monstre -> Labyrinthe : estLibre(nx, ny)

    alt case libre
        Monstre -> Monstre : update position
    else mur
        Monstre -> Monstre : reste en place
    end

end

@enduml