@startuml

actor Joueur

participant Main
participant Labyrinthe
participant Hero
participant Monstre
participant JeuPerso
participant MoteurGraphique

== Lancement du jeu ==

Joueur -> Main : lancer application

Main -> Labyrinthe : new Labyrinthe(fichier.txt)

Labyrinthe -> Hero : création héros (x,y,PV)
Labyrinthe -> Monstre : création monstre (x,y,PV)

Main -> JeuPerso : new JeuPerso(labyrinthe)
Main -> MoteurGraphique : lancerJeu()

MoteurGraphique -> JeuPerso : boucle de jeu

== Déplacement du monstre ==

loop chaque frame

    MoteurGraphique -> JeuPerso : evoluer()

    JeuPerso -> Monstre : deplacer(labyrinthe)

    Monstre -> Monstre : choisir direction aléatoire

    Monstre -> Labyrinthe : estLibre(nx, ny)

    alt case libre
        Monstre -> Monstre : update position
    else mur
        Monstre -> Monstre : reste en place
    end

end

@enduml