@startuml
title Charge du héro
participant Hero
participant Labyrinthe
participant Monstre

Hero -> Hero : Charge(direction, lab, monstre)

loop Jusqu'à 3 cases

    Hero -> Labyrinthe : estLibre(x,y)
    Labyrinthe --> Hero : true / false

    alt Mur rencontré
        Hero --> Hero : arrêt de la charge
    else Case libre

        Hero -> Monstre : estVivant()
        Monstre --> Hero : true / false

        alt Monstre présent sur la case
            Hero -> Monstre : getPos()
            Monstre --> Hero : position
            Hero --> Hero : arrêt de la charge

        else Pas de monstre
            Hero -> Hero : deplacer(x,y)
            Hero --> Hero : nouvelle position
        end

    end

end

Hero --> Hero : fin Charge()

@enduml