@startuml
'https://plantuml.com/sequence-diagram

autonumber

title: Phantome

MainPerso -> JeuPerso: new JeuPerso(lab)
JeuPerso --> Monstre: Authentication Response

== Repetition ==

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml