@startuml
skinparam style strictuml
autonumber

actor Joueur
participant "jeu : JeuPerso" as JP
participant "phantome : Phantome" as Ph
participant "labyrinthe : Labyrinthe" as Lab
participant "hero : Hero" as H

Joueur -> JP : evoluer(commande)

alt phantome != null && phantome.estVivant()
    JP -> Ph : getPos()
    return positionFantome

    JP -> H : getPos()
    return positionHero

    alt memeLigne || memeColonne
        ' L'attaque est gérée ici sans détails
    else Sinon
        JP -> Ph : deplacer(labyrinthe)
        activate Ph

        alt cooldown > 0
            ' cooldown--
        else cooldown == 0
            Ph -> Lab : estLibrePhantome(nx, ny)
            return libre
        end
        deactivate Ph
    end
end
@endum